import Head from 'next/head'
import React from 'react'
import Layout from '../components/layout'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={'bg-cyan-400 flex justify-center text-2xl'}>
          Calhome Frontend
        </main>
      </Layout>
    </>
  )
}
